version: '3.8'

services:
  vjepa2-api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: actus-vjepa2-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=facebook/vjepa2-vitg-fpc64-256
      - MODEL_PATH=/models/vjepa2_weights.pt
      - CLASSIFIER_PATH=/models/classifier_weights.pt
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
      - LOG_LEVEL=INFO
      - DEVICE=cpu  # Use CPU for Docker deployment
      - CORS_ORIGINS=*
    volumes:
      - ../../models:/models:ro  # Mount models directory
      - ../../.env:/app/.env:ro  # Mount environment file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    container_name: actus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - cache

volumes:
  redis_data: 